
import React, { useState } from 'react';
import { generateImage } from '../services/geminiService';
import Loader from './Loader';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    if (!prompt) {
      setError('Please enter a prompt.');
      return;
    }
    setError('');
    setIsLoading(true);
    setGeneratedImage(null);
    try {
      const imageUrl = await generateImage(prompt);
      setGeneratedImage(imageUrl);
    } catch (err) {
      setError('Failed to generate image. The model might have safety restrictions for this prompt.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-gray-800 rounded-lg shadow-xl p-8 space-y-6">
        <div>
          <label htmlFor="image-prompt" className="block text-lg font-medium text-gray-300 mb-2">
            Image Description
          </label>
          <input
            id="image-prompt"
            type="text"
            className="w-full bg-gray-700 border border-gray-600 rounded-md p-4 text-white focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition"
            placeholder="e.g., A futuristic robot managing a Telegram channel"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
          />
        </div>
        <div className="flex justify-end">
          <button
            onClick={handleGenerate}
            disabled={isLoading}
            className="px-8 py-3 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 disabled:bg-indigo-400 disabled:cursor-not-allowed transition-colors duration-300 shadow-lg"
          >
            {isLoading ? 'Generating...' : 'Generate Image'}
          </button>
        </div>
      </div>
      
      {error && <p className="text-red-400 mt-4 text-center">{error}</p>}

      <div className="mt-8 flex justify-center items-center bg-gray-800 rounded-lg shadow-xl p-8 min-h-[400px]">
        {isLoading ? (
          <Loader />
        ) : generatedImage ? (
          <img src={generatedImage} alt="Generated by AI" className="rounded-lg max-w-full h-auto shadow-2xl" />
        ) : (
          <p className="text-gray-500">Your generated image will appear here</p>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
